#
# Copyright (c) 2015-2026 Tomislav Radanovic
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

# Embeds the shader sources listed in shaders/CMakeLists.txt into a
# generated translation unit, shader_registry.cpp, that implements
# rendering_engine::gpu::detail::embedded_shaders(). Each file becomes one
# registry entry keyed by its path relative to shaders/ (forward slashes),
# which is the name gpu::shader_library::source() and the GLSL #include
# directive resolve.
#
# The text is emitted as raw string literals. MSVC caps a single literal
# at 16 KB (C2026), so longer files are split into adjacent literals the
# compiler concatenates; the concatenated total is capped at 64 KB, so a
# file past that is rejected outright.
#
# Invoked as a script (cmake -P) with:
#   -DSHADER_KEYS=<;-list of registry keys>
#   -DSHADER_FILES=<;-list of source paths, parallel to SHADER_KEYS>
#   -DOUTPUT=<path of the .cpp to write>

if(NOT DEFINED SHADER_KEYS OR NOT DEFINED SHADER_FILES OR NOT DEFINED OUTPUT)
    message(FATAL_ERROR "embed_shaders.cmake needs -DSHADER_KEYS=... -DSHADER_FILES=... -DOUTPUT=...")
endif()

list(LENGTH SHADER_KEYS key_count)
list(LENGTH SHADER_FILES file_count)
if(NOT key_count EQUAL file_count)
    message(FATAL_ERROR "embed_shaders.cmake: SHADER_KEYS (${key_count}) and SHADER_FILES (${file_count}) differ in length")
endif()

set(delimiter "AE_SHADER")
set(chunk_size 16000)
set(max_size 65000)

set(out "// Generated by cmake/embed_shaders.cmake from the files listed in\n")
string(APPEND out "// shaders/CMakeLists.txt. Do not edit; change the .glsl sources.\n\n")
string(APPEND out "#include <cstddef>\n\n")
string(APPEND out "#include <rendering_engine/gpu/shader_library.hpp>\n\n")
string(APPEND out "namespace rendering_engine::gpu::shader_library::detail\n{\n")
string(APPEND out "    namespace\n    {\n")
string(APPEND out "        constexpr shader_registry_entry entries[] = {\n")

math(EXPR last "${key_count} - 1")
foreach(index RANGE ${last})
    list(GET SHADER_KEYS ${index} key)
    list(GET SHADER_FILES ${index} file)

    if(NOT EXISTS "${file}")
        message(FATAL_ERROR "embed_shaders.cmake: shader source '${file}' (key '${key}') does not exist")
    endif()

    file(READ "${file}" content)
    string(LENGTH "${content}" length)

    if(length GREATER max_size)
        message(FATAL_ERROR "embed_shaders.cmake: '${key}' is ${length} bytes; the embedded literal limit is ${max_size}")
    endif()

    string(FIND "${content}" ")${delimiter}\"" collision)
    if(NOT collision EQUAL -1)
        message(FATAL_ERROR "embed_shaders.cmake: '${key}' contains the raw-literal delimiter ')${delimiter}\"'")
    endif()

    string(APPEND out "            {\"${key}\",\n")
    if(length EQUAL 0)
        string(APPEND out "             \"\",\n")
    else()
        set(pos 0)
        while(pos LESS length)
            math(EXPR remaining "${length} - ${pos}")
            if(remaining GREATER chunk_size)
                set(take ${chunk_size})
            else()
                set(take ${remaining})
            endif()
            string(SUBSTRING "${content}" ${pos} ${take} chunk)
            string(APPEND out "             R\"${delimiter}(${chunk})${delimiter}\"\n")
            math(EXPR pos "${pos} + ${take}")
        endwhile()
        string(APPEND out "             ,\n")
    endif()
    string(APPEND out "             ${length}},\n")
endforeach()

string(APPEND out "        };\n")
string(APPEND out "    } // namespace\n\n")
string(APPEND out "    const shader_registry_entry* embedded_shaders(std::size_t& count)\n")
string(APPEND out "    {\n")
string(APPEND out "        count = sizeof(entries) / sizeof(entries[0]);\n")
string(APPEND out "        return entries;\n")
string(APPEND out "    }\n")
string(APPEND out "} // namespace rendering_engine::gpu::shader_library::detail\n")

# Only rewrite when the text changed so an unchanged registry does not
# recompile and relink.
set(existing "")
if(EXISTS "${OUTPUT}")
    file(READ "${OUTPUT}" existing)
endif()
if(NOT existing STREQUAL out)
    file(WRITE "${OUTPUT}" "${out}")
endif()
